server:
  port: 8761

eureka:
  instance:                 #定义Eureka实例
    hostname: localhost     #Eureka实例所在的主机名
  client:
    registerWithEureka: false   #表示是否将自己注册到Eureka Server上，默认为true
    fetchRegistry: false        #表示是否从Eureka Server上获取注册信息，默认为true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: eurka-server